### PR TITLE
Update deliverables

### LINKED ISSUE #3: update pre-course
- [x] This feature  developed on a branch called `update-deliverables`
- [x] restructure module delivrables.
- [x] add `lesson plan`
- [ ] update `suggested study`

### PR DESCRIPTION
**Pull request by sammou00**
- [x] restructure `deliverables` 
- [x] add `lesson plan`
- [x] update suggested study
- [x] update `README.md`
- [x] add `package.json`
- [x] add GItHub `action`

### CODE REVIEW

**Comment by talmurshidi** [comment]
Nice, I will use the same branch to update some stuff then let you know.

**Comment by talmurshidi** [comment]
I liked the new folders structures. 
"Divide and Conquer" I used it when writing classes and methods.

I created a new branch `update-precourse-v2`, I will merge it into your branch with the updates so you can see the new changes. I'm working on it.

I prefer to kepp:

- `Git Setup` because some learners had problem with it.
- Recommended extensions, the old one has deprecated extensions and nowadays it is build in VSCode.

**Comment by sammou00** [comment]
> I liked the new folders structures. "Divide and Conquer" I used it when writing classes and methods.
> 
> I created a new branch `update-precourse-v2`, I will merge it into your branch with the updates so you can see the new changes. I'm working on it.
> 
> I prefer to kepp:
> 
> * `Git Setup` because some learners had problems with it.
> * Recommended extensions, the old one has deprecated extensions and nowadays it is built in VSCode.

Ok,
-  I will add the setup section again.
- I still can add more info to make it more clear, especially vs code extensions.
- maybe I can add a package.json, with lining packages.

**Comment by talmurshidi** [comment]
You can use [lint.yml](https://github.com/HackYourFutureBelgium/workflows/blob/master/.github/workflows/lint.yml)
Maybe you can remove `Setup node` from it.
`- name: Setup node`
`uses: actions/setup-node@v3`

**Comment by samirm00** [comment]
> You can use [lint.yml](https://github.com/HackYourFutureBelgium/workflows/blob/master/.github/workflows/lint.yml) Maybe you can remove `Setup node` from it. `- name: Setup node` `uses: actions/setup-node@v3`

I did, but it seems it can't find package.json.

**Comment by talmurshidi** [comment]
`devDependencies` is empty so you will see `ls-lint: not found` error

**Comment by sammou00** [comment]
> `devDependencies` is empty so you will see `ls-lint: not found` error

fixed.

**Review by talmurshidi — APPROVED** [review]

**Pull request merged**
